#!/usr/bin/env zsh
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset pipefail no_clobber

user=$USER
key=$(< ~/.ssh/authorized_keys)

# ISO from: https://www.dragonflybsd.org/download/
# 
# qemu-img create -f qcow2 disks//dragonfly-6.2.2.qcow2 8G
# 
# Use "legacy BIOS"
<<-EOF
	#!/bin/sh
	# DragonFly BSD setup script
	set -euC

	# Add line to file only if it's not in there yet.
	add() { grep -q "\$1" "\$2" || echo "\$1" >>"\$2" }

	: >!/etc/motd                                 # No login messages
	add 'boot_mute="YES"'    /boot/loader.conf    # Don't wait for the bootloader
	add 'autoboot_delay="0"' /boot/loader.conf
	add 'ifconfig_em0="DHCP"' /etc/rc.conf        # Enable networking
	add 'sshd_enable="YES"'   /etc/rc.conf        # Enable sshd
	/etc/rc.d/netif start                         # Start network
	/etc/rc.d/sshd restart

	# fdisk -B ad0

	# Add user
	grep -q "^$user:" /etc/passwd || pw user add -mG wheel -n "$user"
	install -do "$user" -g "$user" "/home/$user/.ssh"
	add "$key" "/home/$user/.ssh/authorized_keys"

	pkg install -y go                             # Install Go
EOF
