#!/usr/bin/env zsh
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset pipefail no_clobber

user=$USER
key=$(cat ~/.ssh/authorized_keys)

# Setup; we can use -serial stdio in qemu
#
# https://fadeevab.com/how-to-setup-qemu-output-to-console-and-automate-using-shell-script/
# https://stackoverflow.com/q/3146013/660921
#
# Need to look into that
<<-EOF
	#!/bin/sh
	#
	# FreeBSD setup script

	# Lots of wasted space.
	rm -rf /usr/lib/debug

	# Don't wait for the bootloader.
	echo 'boot_mute="YES"'    >> /boot/loader.conf
	echo 'autoboot_delay="0"' >> /boot/loader.conf

	# Enable sshd
	echo 'sshd_enable=YES' >> /etc/rc.conf
	service sshd start

	# Add user, setup our key.
	echo passwd | pw user add -G wheel -n $user -h 0
	install -do $user -g $user /home/$user/.ssh
	echo "$key" >> /home/$user/.ssh/authorized_keys

	# No login messages.
	: >/etc/motd.template
	: >/var/run/motd

	# Install Go.
	pkg bootstrap
	pkg install -y go
EOF
