#!/usr/bin/env zsh
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset pipefail no_clobber

user=$USER
key=$(< ~/.ssh/authorized_keys)

# Setup; we can use -serial stdio in qemu
#
# https://fadeevab.com/how-to-setup-qemu-output-to-console-and-automate-using-shell-script/
# https://stackoverflow.com/q/3146013/660921
#
# Need to look into that
<<-EOF
	#!/bin/sh
	# FreeBSD setup script
	set -euC

	# Add line to file only if it's not in there yet.
	add() { grep -q "\$1" "\$2" || echo "\$1" >>"\$2" }

	rm -rf /usr/lib/debug                        # Lots of wasted space
	: >!/etc/motd.template; : >!/var/run/motd    # No login messages
	add 'boot_mute="YES"'    /boot/loader.conf   # Don't wait for the bootloader
	add 'autoboot_delay="0"' /boot/loader.conf
	add 'sshd_enable=YES'    /etc/rc.conf        # Enable sshd
	sed -i 's/^#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config
	service sshd start ||:

	# Add user
	grep -q "^$user:" /etc/passwd || pw user add -mG wheel -n "$user"
	install -do "$user" -g "$user" "/home/$user/.ssh"
	add "$key" "/home/$user/.ssh/authorized_keys"

	pkg bootstrap                                # Install Go
	pkg install -y go
EOF
