#!/usr/bin/env zsh
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset pipefail no_clobber

user=$USER
key=$(< ~/.ssh/authorized_keys)

<<-EOF
	#!/bin/sh
	# NetBSD setup script
	set -euC

	# Add line to file only if it's not in there yet.
	add() { grep -q "\$1" "\$2" || echo "\$1" >>"\$2" }

	sed -i 's/^timeout=5$/timeout=0/' /boot.cfg   # Don't wait for the bootloader.
	: >!/etc/motd                                 # No login messages.
	add 'dhcpcd=YES'          '/etc/rc.conf'      # Enable networking and sshd
	add 'dhcpcd_flags=vioif0' '/etc/rc.conf'
	add 'sshd=YES'            '/etc/rc.conf'
	service dhcpcd start ||:
	service sshd start   ||:

	# Add user, setup our key.
	grep -q "^$user:" /etc/passwd || useradd -mG wheel $user
	install -do "$user" -g "$user" "/home/$user/.ssh"
	add "$key" "/home/$user/.ssh/authorized_keys"

	# Install Go.
	export PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/\$(uname -p)/\$(uname -r|cut -f '1 2' -d.)/All/"
	pkg_add pkgin
	pkgin -y install ca-certificates go
	ln -fs /usr/pkg/bin/go117 /usr/pkg/bin/go
EOF
