#!/usr/bin/env zsh
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset pipefail no_clobber

user=$USER
key=$(< ~/.ssh/authorized_keys)

<<-EOF
	#!/bin/sh
	# OpenBSD setup script
	set -euC

	# Add line to file only if it's not in there yet.
	add() { grep -q "\$1" "\$2" || echo "\$1" >>"\$2" }

	add 'set timeout 1' /etc/boot.conf  # Don't wait for the bootloader (0 is forever)
	: >!/etc/motd                       # No login messages

	# Add user, setup our key.
	grep -q "^$user:" /etc/passwd || useradd -mG wheel $user
	install -do "$user" -g "$user" "/home/$user/.ssh"
	add "$key" >> /home/$user/.ssh/authorized_keys

	pkg_add go                          # Install Go
EOF
